### ISSUE TITLE
Support human-readable file size output

### ISSUE THREAD

**Issue by sphr2k** [joonro/Get-ChildItem-Color#16]
Hi,
thanks for this great cmdlet. I'd love to have human-readable file size output instead of the simple byte count that PowerShell provides. A way to do this is described [here](https://superuser.com/questions/468782/show-human-readable-file-sizes-in-the-default-powershell-ls-command). However, when using `format-table` with `Get-ChildItemColor`, the colorization is lost. Any way around this?
Thanks, Jan

**Comment by joonro** [comment]
Hi -

This looks interesting. I only tried the second example from the link you provided. It does not work if you use it like this:

```powershell
Get-ChildItemColor  | Select-Object Name, @{Name="Size";Expression={Format-FileSize($_.Length)}}
```

because `Get-ChildItemColor` just changes `$Host.UI.RawUI.ForegroundColor` right before printing an item, and the pipe will not get the color information.

However, if you do the following:

```powershell
Function Format-FileSize() {
    Param ([int]$size)
    If     ($size -gt 1TB) {[string]::Format("{0:0.00} TB", $size / 1TB)}
    ElseIf ($size -gt 1GB) {[string]::Format("{0:0.00} GB", $size / 1GB)}
    ElseIf ($size -gt 1MB) {[string]::Format("{0:0.00} MB", $size / 1MB)}
    ElseIf ($size -gt 1KB) {[string]::Format("{0:0.00} kB", $size / 1KB)}
    ElseIf ($size -gt 0)   {[string]::Format("{0:0.00} B", $size)}
    Else                   {""}
}

$Host.UI.RawUI.ForegroundColor = "Red"

Get-ChildItem | Select-Object Name, @{Name="Size";Expression={Format-FileSize($_.Length)}}
```

You will see that everything is red now, so one way to do this is creating a function which incorporates the coloring as well as `Select-Object Name, @{Name="Size";Expression={Format-FileSize($_.Length)}}` part. 

Unfortunately I don't have time to implement this at the moment, but I would be happy to accept a PR if you want to open one. I'm sorry!

**Comment by sphr2k** [comment]
Hi,
thanks for you reply :) I'm afraid I'm not very capable when it comes to more complex PowerShell stuff - maybe I'll to get it working if I find the time. Cheers, Jan

**Comment by joonro** [comment]
Hi,

I just incorporated [PSColor](https://github.com/Davlind/PSColor)'s implementation, and this should be working now.
