### ISSUE TITLE
Performance, etc.

### ISSUE THREAD

**Issue by Velocet** [joonro/Get-ChildItem-Color#8]
Hi there,

i really appreciate your effort but i have to admit that your script is a complete mess. There are so many performance issues and also it seems that no coding standard was used. Even the naming convention of the whole script/function is wrong: `Get-ChildItem-Color` should be `Get-ChildItemColor`.

Please have a look at [PSColor](https://github.com/Davlind/PSColor) for a much more better (and faster) solution.
Even this 8 year old script solves it way better then your version: [Get-ChildItemColor](http://poshcode.org/876)

I wouldn't recommend using it and normally would make a pull request... But since this is a complete mess it would be pointless. Maybe a short sentence in the readme would be helpful.

**Comment by joonro** [comment]
Hi - no one is forcing you to use it so I really don't see the point of your issue, unless you just want to criticize my code, in which case it is not a productive approach. But you are right, I know the code could be better. I guess I should say I'm sorry :) Unfortunately these days I'm extremely busy so I haven't had time to improve the code.

Regarding your suggestion of other packages (such as [PSColor](https://github.com/Davlind/PSColor)), I just tried it, but it was not clear how to get color for `Get-ChildItem | Format-Wide` so I don't think it is a proper replacement. You see getting `ls` equivalent was a major motivator for this code - it is not that straightforward to get coloring with `Format-Wide` - you basically have to rewrite everything. Otherwise I would have used the 8 year old script that you mentioned. Thanks for the pointers to other scripts though. I would love to find a better script which provides a consistent coloring for `Format-Wide`. 

I would welcome a PR which will improve the code, so please feel free to open one if you want.

**Comment by joonro** [comment]
I will close this issue - I don't think you understand what this script does. Feel free to open another issue or a PR if you have something constructive to contribute.
